- hosts: all
  gather_facts: false
  tasks:
  - name: Copy proxy files
    copy:
      src: proxy
      dest: /srv/cloakmail
      mode: preserve
      group: appadmin
      directory_mode: "2770"
  - name: Run proxy
    docker_compose:
      project_src: /srv/cloakmail/proxy
      state: present
