- hosts: all
  gather_facts: false
  tasks:
  - name: Copy infra files
    copy:
      src: cloakmail_infra
      dest: /srv/cloakmail
      mode: preserve
      group: appadmin
      directory_mode: "2770"
  - name: Run infra services
    docker_compose:
      project_src: /srv/cloakmail/cloakmail_infra
      state: present
  
