version: "3"  

services:
  cloakmail:
    image: dhet/cloakmail
    # container_name: cloakmail-app # container name cannot be set due to flaws in rolling update script
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: app.cloakmail.org
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: app.cloakmail.org

      SPRING_PROFILES_ACTIVE: prod
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://auth.cloakmail.org/auth/realms/cloakmail/protocol/openid-connect/certs
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/
      CLOAKMAIL_DOMAIN: cloakmail.org
      CLOAKMAIL_MODE: multiuser
      CLOAKMAIL_LOG_PROCESSING_ENABLED: "true"
      CLOAKMAIL_KEYCLOAK_BASE_URL: https://auth.cloakmail.org/auth
    env_file:
      - .cloakmail.env
    # logging:
    #   driver: aws
    #   options:
    #     awslogs-region: eu-central-1
    #     awslogs-group: cloakmail
    #     awslogs-create-group: "true"
    networks:
      - proxy_default
      - cloakmail

  postfix:
    container_name: postfix
    image: dhet/postfix-pg:latest
    container_name: postfix
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      CONF_SMTP_HELO_NAME: cloakmail.org
      CONF_MYHOSTNAME: mx.cloakmail.org
      CONF_MYDOMAIN: cloakmail.org
      CONF_SMTP_ALWAYS_SEND_EHLO: 'yes'

      ### Log to pg
      POSTGRES_LOG_HOST: db
      POSTGRES_LOG_DB: postgres
      POSTGRES_LOG_TABLE: postfix_log

      ### Aliases
      POSTGRES_HOSTS: db
      POSTGRES_ALIAS_DB: postgres
      POSTGRES_VALIAS_QUERY: select dest_addr from alias_view where alias_addr='%s'
      CONF_VIRTUAL_ALIAS_DOMAINS: cloakmail.org

      ### TLS outgoing mail
      CONF_SMTP_TLS_KEY_FILE: /etc/ssl/private/mx.cloakmail.org.key
      CONF_SMTP_TLS_CERT_FILE: /etc/ssl/private/mx.cloakmail.org.crt
      CONF_SMTP_TLS_SECURITY_LEVEL: may # Use TLS whenever possible
      CONF_SMTP_TLS_LOGLEVEL: 1

      ### TLS incoming mail
      CONF_SMTPD_TLS_KEY_FILE: /etc/ssl/private/mx.cloakmail.org.key
      CONF_SMTPD_TLS_CERT_FILE: /etc/ssl/private/mx.cloakmail.org.crt
      CONF_SMTPD_TLS_SECURITY_LEVEL: may # Use TLS whenever possible
      CONF_SMTPD_TLS_LOGLEVEL: 1

      ### Nginx proxy + Letsencrypt companion
      VIRTUAL_HOST: mx.cloakmail.org
      LETSENCRYPT_HOST: mx.cloakmail.org

    env_file: .postfix.env
    volumes:
      - proxy_certs:/etc/ssl/private
    ports:
      - "25:25"
    networks:
      - cloakmail

  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - 54321:5432
    env_file: .postgres.env
    volumes:
      - cloakmail_db:/var/lib/postgresql/data
      - ./initdb/001_init.sh:/docker-entrypoint-initdb.d/001_init.sh
    networks:
      - cloakmail

  keycloak:
    image: dhet/cloakmail-keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    env_file:
      - .keycloak.env
    environment:
      VIRTUAL_HOST: auth.cloakmail.org
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: auth.cloakmail.org
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - db
    networks:
      - proxy_default
      - cloakmail

networks:
  cloakmail:
  proxy_default:
    external: true

volumes:
  cloakmail_db:
  proxy_certs:
    external: true

      
